### ISSUE TITLE
no implicit conversion of FFI::MemoryPointer into String (TypeError)

### ISSUE THREAD

**Issue by ghost** [chef/win32-service#15]
When I try to start any daemon (including the demo daemon), I get: The service is not responding to the control function.

When I comment out the redirects to NUL in mainloop, the following is printed to stdout:
(eval):3:in 'call': no implicit conversion of FFI::MemoryPointer into String (TypeError)
        from (eval):3:in 'WaitForMultipleObjects'
        from ruby/lib/ruby/gems/2.0.0/gems/win32-service-0.8.4/lib/win32/daemon.rb:262:in 'mainloop'
        from ruby/lib/ruby/gems/2.0.0/gems/win32-service-0.8.4/lib/win32/daemon.rb:206:in 'mainloop'
        from daemon.rb:93:in '&lt;main&gt;'

Environment information: ruby 2.0.0p353 (2013-11-22) [x64-mingw32]
bigdecimal (1.2.5, 1.2.0)
deep_merge (1.0.1, 1.0.0)
ffi (1.9.3 x64-mingw32, 1.9.0)
io-console (0.4.2)
json (1.8.1, 1.7.7)
minitar (0.5.4)
minitest (5.2.3, 4.3.2)
psych (2.0.4, 2.0.0)
rake (10.1.1, 0.9.6)
rdoc (4.1.1, 4.0.0)
rgen (0.6.6, 0.6.5)
stomp (1.3.2, 1.2.9)
structured_warnings (0.1.4)
sys-admin (1.6.2)
test-unit (2.5.5, 2.0.0.0)
win32-api (1.5.1 universal-mingw32, 1.4.8)
win32-dir (0.4.6, 0.4.3)
win32-eventlog (0.6.0, 0.5.3)
win32-process (0.7.4, 0.6.5)
win32-security (0.2.4)
win32-service (0.8.4)
win32-taskscheduler (0.3.0, 0.2.2)
win32console (1.3.2)
windows-api (0.4.2)
windows-pr (1.2.3)

**Comment by voxdei** [comment]
I'm facing a similar issue, like in rare occasion this keeps failing the service from properly booting, while when I deploy the exact same piece of code on different machine it just works, making the "how to reproduce it" very hard to formulate

Still we do have a machine that keeps failing, and I was able to play with it a little; I added a basic log (writting to a file) around pretty much any line inside the `mainloop` method, and that alone "fixed" the problem, making the service up and running for windows very quickly

I then removed the logging, and added a basic `sleep(0.1)` instead of writting to a file, one a time

When I put that sleep within the the following loop as such

```ruby
      while (index = WaitForMultipleObjects(2, events, 0, 1000)) == WAIT_TIMEOUT
        sleep(0.1)
      end
```

my service always started very quickly, the moment I remove it I get back with my timeout issue and windows can't start it

So I'm suspecthing it has to come from that  `WaitForMultipleObjects` method somehow, but didn't push it further yet
